"""
Self defined domain-specific stop-word list.
"""
from sklearn.feature_extraction import stop_words

__author__ = 'kensk8er'

extra_stopwords = {'hsbc', 'view', 'click', 'mailto', 'nomura', 'message', 'january', 'february', 'march', 'april',
                   'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december', 'jan', 'feb', 'mar',
                   'apr', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec', 'barclay', 'survey', 'invitation', 'daily',
                   'weekly', 'monthly', 'highlight', 'isi', 'report', 'portfolio', 'strategy', 'jpy', 'analysis',
                   'technical', 'register', 'reminder', 'survey', 'citi', 'merrill', 'lynch', 'goldman', 'sachs',
                   'morgan', 'stanley', 'chase', 'Lloyd', 'attach', 'nomura', 'norge', 'bank', 'recommendation',
                   'insight', 'comment', 'morning', 'gs', 'week', 'day', 'month', 'year', 'minute', 'second', 'hour',
                   'two', 'news', 'data', 'market', 'ub', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday',
                   'saturday', 'sunday', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', 'reid', 'research', 'summary',
                   'ft', 'comment', 'wsj', 'outlook', 'update', 'reading', 'note', 'hfe', 'snapshot', 'thought', 'edt',
                   'gmt', 'natixis', 'research', 'intraday', 'chosen', 'running', 'cent', 'dollar', 'ordinary', 'ad',
                   'subscription', 'access', 'internet', 'web', 'email', 'mail', 'app', 'pc', 'product', 'analyst',
                   'use', 'jpmorgan', 'near', 'time', 'unsubscribe', 'subscription', 'form', 'read', 'hundred',
                   'thousand', 'million', 'billion', 'trillion', 'forecast', 'expect', 'expectation', 'detail',
                   'number', 'curve', 'end', 'learn', 'member', 'offer', 'estimate', 'index', 'line', 'ensure',
                   'person', 'book', 'material', 'state', 'smart', 'appearance', 'category', 'percent', 'performance',
                   'bloomberg', 'record', 'program', 'status', 'group', 'forward', 'let', 'thank', 'dear',
                   'distribution', 'position', 'night', 'phone', 'chart', 'buy', 'sell', 'target', 'access', 'land',
                   'communication', 'reference', 'document', 'attachment', 'recipient', 'calendar', 'confirmation',
                   'backlog', 'word', 'overview', 'yesterday', 'today', 'tomorrow', 'last', 'next', 'previous', 'final',
                   'summarize', 'quieter', 'conundrum', 'package', 'whilst', 'source', 'client', 'distribution', 'core',
                   'headline', 'increase', 'right', 'ac', 'download', 'matrix', 'refer', 'fall', 'monitor', 'opinion',
                   'theme', 'short', 'area', 'power', 'security', 'address', 'browser', 'paste', 'copy', 'close',
                   'stop', 'start', 'sender', 'representation', 'buy', 'sell', 'citigroup', 'citifx', 'citibank',
                   'usdjpy', 'emailplease', 'jp-morgan', 'prediction', 'usdcny', 'subscribe', 'subscriber',
                   'profileemail', 'usdoz', 'eurusd', 'jpybn', 'know', 'password', 'flash', 'rge', 'roubini', 'mom',
                   'yoy', 'roubini-global-economics', 'balance', 'sheet', 'first', 'third', 'fourth', 'fifth', 'sixth',
                   'seventh', 'eighth', 'ninth', 'tenth', 'sgh', 'berenberg', 'eurgbp', 'hyperlink', 'db', 'weekender',
                   'live', 'connect', 'anthony', 'deutsche', 'askin', 'kristen', 'brinkmann', 'alexander', 'bryce',
                   'steven', 'bulega', 'cahill', 'michael', 'carola', 'bardelli', 'christensen', 'ulrik', 'colin',
                   'tan', 'ludovic', 'dabrowski', 'matt', 'rsch', 'danny', 'ive', 'dominic', 'konstam', 'dooling',
                   'daniel', 'felicia', 'hendrix', 'fordham', 'tina', 'baba', 'hatzius', 'tilton', 'brook', 'lake',
                   'trivedi', 'garner', 'jonathan', 'garnett', 'amelia', 'george', 'buckly', 'gille', 'moec', 'giret',
                   'anne', 'laure', 'goldberg', 'ithai', 'graham', 'maria', 'grizzle', 'benjamin', 'herald', 'van',
                   'der', 'linde', 'cfa', 'horsey', 'alice', 'fi', 'tsy', 'cap', 'mkts', 'james', 'coxon', 'jim',
                   'reid', 'john', 'normand', 'jone', 'gareth', 'joseph', 'lavorgna', 'lazzerini', 'ettore', 'lee',
                   'thomas', 'lightowler', 'lin', 'li', 'linan', 'liu', 'louisa', 'lam', 'makino', 'makoto', 'stringa',
                   'mark', 'wall', 'moec', 'mauro', 'spencer', 'tong', 'narminio', 'aurelien', 'nick', 'burn', 'paone',
                   'fabiana', 'perry', 'kojodjojo', 'peter', 'hooper', 'torsten', 'slok', 'sidorov', 'pria', 'bakhshi',
                   'razzak', 'aisha', 'robert', 'mellman', 'sgh', 'advisor', 'saliba', 'nadia', 'sameer', 'goel',
                   'schmieding', 'holger', 'schulz', 'christian', 'seb', 'barker', 'sellwood', 'ross', 'shuyan', 'wu',
                   'small', 'cameron', 'smalley', 'staniford', 'stephen', 'stakhiv', 'sun', 'cfa', 'tellisa', 'clarke',
                   'teves', 'join', 'tobieson', 'joakim', 'tully', 'edel', 'walsh', 'paul', 'wilson', 'peter', 'wolff',
                   'patrick', 'wood', 'yalcin', 'ekin', 'van', 'wagensveld', 'suzan', 'anna', 'zadornova', 'bhanu',
                   'baweja', 'cynthia', 'cheng', 'emily', 'benn', 'eve', 'raoul', 'qi', 'chen', 'wang', 'tao', 'andrew',
                   'cate', 'angela', 'barber', 'brian', 'boucher', 'prospectus', 'edel', 'tully', 'gustavo', 'arteta',
                   'gyorgy', 'kovacs', 'inigo', 'fraser', 'jenkin', 'jason', 'perl', 'normand', 'julien', 'garran',
                   'larry', 'hatheway', 'loncust', 'manik', 'narain', 'martin', 'lueck', 'nelson', 'ramin', 'nakisa',
                   'reinhard', 'cluse', 'reto', 'huenerwadel', 'stephane', 'deo', 'major', 'william', 'darwin', 'adam',
                   'richardson', 'aditya', 'chordia', 'adrian', 'mowat', 'david', 'aserkoff', 'pedro', 'martin', 'josh',
                   'klaczek', 'sanaya', 'tavaria', 'agata', 'urbanska', 'giner', 'alastair', 'newton', 'alejandro',
                   'martinez', 'cruz', 'alex', 'roever', 'white', 'alexander', 'morozov', 'ander', 'mielsen', 'andre',
                   'carvalho', 'loes', 'de', 'silva', 'arindam', 'sandilya', 'artem', 'biryukov', 'ben', 'laidler',
                   'benjamin', 'mandel', 'bert', 'lourenco', 'bertrand', 'delgado', 'bob', 'janjuah', 'bruce', 'kasman',
                   'hansley', 'loey', 'lupton', 'warden', 'carsar', 'maasry', 'charlene', 'saltzman', 'chris',
                   'attfield', 'clyde', 'wardle', 'constantin', 'jancso', 'crystal', 'zhao', 'fenn', 'grosvenor',
                   'daragh', 'maher', 'bloom', 'faulkner', 'mackie', 'watt', 'dennis', 'debusschere', 'devendran',
                   'mahendran', 'di', 'luo', 'dick', 'hokenson', 'dilip', 'shahani', 'ed', 'hyman', 'edward', 'morse',
                   'elise', 'badoy', 'elizabeth', 'ernie', 'tedeschi', 'magazine', 'francis', 'khagendra', 'gupta',
                   'fabio', 'bassi', 'fordham', 'tina', 'francesc', 'lleal', 'meggyesi', 'francisco', 'schumacher',
                   'will', 'frank', 'frederic', 'neumann', 'fredrik', 'nerbrand', 'garry', 'evan', 'christou',
                   'gianluca', 'salford', 'gile', 'patternson', 'gordian', 'kemen', 'greg', 'fuzesi', 'han', 'lorenzen',
                   'howard', 'wen', 'inigo', 'fraser', 'ipreo', 'ivan', 'zubo', 'izumi', 'devalier', 'jabaz', 'mathai',
                   'jae', 'yang', 'jaewoo', 'nakajima', 'james', 'barne', 'pomeroy', 'walsh', 'feroli', 'janet',
                   'henry', 'javier', 'finkman', 'jeanette', 'jenny', 'lai', 'jimmy', 'coonan', 'jitendra', 'sriram',
                   'lomax', 'holly', 'huffman', 'zhu', 'stubbs', 'morgenstern', 'mellman', 'joyce', 'chang', 'juan',
                   'carlos', 'ju', 'karen', 'ward', 'kevin', 'hebner', 'logan', 'krishana', 'guha', 'lan', 'lawrence',
                   'dyer', 'leif', 'eskesen', 'lorena', 'dominguez', 'loui', 'odette', 'ma', 'xiaoping', 'malcolm',
                   'barr', 'protopapa', 'marina', 'valle', 'marjorie', 'hernandez', 'mark', 'diver', 'mcdonald',
                   'schofield', 'mathilde', 'lemoine', 'king', 'matthew', 'dabrowski', 'meera', 'chandan', 'melis',
                   'metiner', 'mufg', 'murat', 'toprak', 'ulgen', 'murray', 'gunn', 'natixis', 'nalin', 'chutchotitham',
                   'nikolaos', 'panigirtzoglou', 'omfif', 'secretariat', 'oscar', 'sloterbeck', 'charlene', 'pablo',
                   'pankaj', 'mataney', 'bloxham', 'mackel', 'hooper', 'sullivan', 'pin', 'ru', 'tan', 'qu', 'hongbin',
                   'ramiro', 'blazquez', 'raphael', 'brun', 'aguerre', 'ratul', 'roy', 'lynch', 'parke', 'robostox',
                   'ronald', 'man', 'roubini', 'ryan', 'sajjid', 'chinoy', 'sally', 'auld', 'sanaya', 'tavaria',
                   'mowat', 'scott', 'chronert', 'sergio', 'shora', 'haydari', 'simon', 'well', 'stacy', 'antczak',
                   'cfa', 'su', 'sian', 'lim', 'subhrajit', 'banerjee', 'junwei', 'teresa', 'cascino', 'terry', 'haine',
                   'theologis', 'chapsali', 'tohru', 'sasaki', 'trinh', 'nguyen', 'le', 'vicki', 'stern', 'victor',
                   'fu', 'wai', 'shin', 'chan', 'wietse', 'nijenhuis', 'wilson', 'chin', 'xavier', 'botteri', 'yi',
                   'hu', 'zhi', 'ming', 'zhang', 'brought', 'usdinr', 'usdkrw', 'usdidr', 'gravekal-dragonomic',
                   'credit-suisse', 'ipad', 'iphone', 'android', 'apple', 'app', 'gbpusd', 'net', 'niplc', 'eurjpy',
                   'redirect', 'here', 'article', 'about', 'use', 'disambiguation', 'confuse', 'cookies'}

extended_stopwords = stop_words.ENGLISH_STOP_WORDS.union(extra_stopwords)